In [3]:
!pip install gym


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
!pip install pygame


   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB 281.8 kB/s eta 0:00:38
   ---------------------------------------- 0.1/10.6 MB 328.2 kB/s eta 0:00:33
    --------------------------------------- 0.2/10.6 MB 706.2 kB/s eta 0:00:15
   - -------------------------------------- 0.4/10.6 MB 1.6 MB/s eta 0:00:07
   ---- ----------------------------------- 1.2/10.6 MB 4.3 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/10.6 MB 8.2 MB/s eta 0:00:01
   --------------- ------------------------ 4.2/10.6 MB 10.8 MB/s eta 0:00:01
   -------------------- ------------------- 5.4/10.6 MB 12.9 MB/s eta 0:00:01
   ------------------------- -------------- 6.8/10.6 MB 14.6 MB/s eta 0:00:01
   ------------------------------ --------- 8.2/10.6 MB 15.9 MB/s eta 0:00:01
   -------


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import gym

## Naive implementation

In [7]:
# Create the CartPole-v1 environment with render_mode set to 'human'
env_v1 = gym.make('CartPole-v1', render_mode='human')

# Reset the environment and return the initial observation
obs, info = env_v1.reset()

for _ in range(1000):
    env_v1.render()
    
    # Take a random action
    action = env_v1.action_space.sample()
    
    # Perform a step in the environment
    obs, reward, terminated, truncated, info = env_v1.step(action)
    
    # Check if the episode is terminated, then reset the environment
    if terminated or truncated:
        obs, info = env_v1.reset()

env_v1.close()

c:\Python312\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


## Understanding `env.step`

As mentioned in the documentation page, each environment is separated into different episodes, with `done=True` indicating that the specific episode has ended. Thus, we need to call reset there. For this, we need to understand what `env.step(action)` does and returns. `env.step(action)` takes the next step in the environment by performing the action specified by `action` and returns a tuple:
- observation: This is environment specific and represents our observation of the environment after taking the action specified in `env.step(action)`.
- reward: The reward we received upon performing the action.
- done: This is the parameter we discussed about. We need to monitor this and call `env.reset()` when `done=True`.
- info: Additional information for debugging

In [8]:
env_v0 = gym.make('CartPole-v0', render_mode='human')

for i_episode in range(20):
    # Reset the environment and return the initial observation
    observation, info = env_v0.reset()
    
    for t in range(1000):
        env_v0.render()
        print(observation)
        
        # Take a random action
        action = env_v0.action_space.sample()
        
        # Perform a step in the environment
        observation, reward, terminated, truncated, info = env_v0.step(action)
        
        if terminated or truncated:
            print(f'Episode #{i_episode} finished after {t} timesteps')
            break

env_v0.close()

c:\Python312\Lib\site-packages\gym\envs\registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(


[ 0.02022988 -0.01467793 -0.02253062  0.02847488]
[ 0.01993632 -0.20946965 -0.02196112  0.31396487]
[ 0.01574693 -0.01404185 -0.01568183  0.0144378 ]
[ 0.01546609 -0.20893544 -0.01539307  0.30213198]
[ 0.01128738 -0.40383464 -0.00935043  0.58992076]
[ 0.00321069 -0.20858304  0.00244799  0.29430717]
[-0.00096097 -0.4037398   0.00833413  0.58776116]
[-0.00903577 -0.20873556  0.02008935  0.29771513]
[-0.01321048 -0.40413803  0.02604365  0.59666556]
[-0.02129324 -0.59961456  0.03797697  0.8974369 ]
[-0.03328553 -0.40502742  0.0559257   0.61692923]
[-0.04138608 -0.60088426  0.06826429  0.92668873]
[-0.05340376 -0.4067472   0.08679806  0.6562155 ]
[-0.06153871 -0.21293397  0.09992237  0.3920767 ]
[-0.06579739 -0.01936153  0.10776391  0.13249469]
[-0.06618462 -0.21584888  0.1104138   0.4571373 ]
[-0.0705016  -0.41234446  0.11955655  0.7824816 ]
[-0.07874848 -0.21905077  0.13520618  0.52967674]
[-0.0831295  -0.41578978  0.14579971  0.8617216 ]
[-0.09144529 -0.612564    0.16303414  1.1964648 ]


## Understanding agent actions
The environments in gym have `Space` objects which describe the valid actions and observations


In [10]:
print(env_v1.action_space)  # Should print: Discrete(2)

Discrete(2)


In [11]:
print(env_v1.observation_space)

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)


Basically, `Discrete` specifies the range of non-negative values. <br>
This means `Discrete(3)` means that the action can take values `{0, 1, 2}`. <br>
`Box` represents an n-dimensional (here, n=4) value.